[mypy]
ignore_errors = False
warn_unused_configs = True
warn_redundant_casts = True
ignore_missing_imports = False
disallow_untyped_defs = True
disallow_incomplete_defs = True
enable_error_code = possibly-undefined

[mypy-hpgeom]
ignore_missing_imports = True
ignore_errors = True

[mypy-lsst.sphgeom.*]
ignore_missing_imports = False
ignore_errors = False
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_equality = True
warn_unreachable = True
warn_unused_ignores = True

[mypy-lsst.sphgeom._sphgeom]
ignore_missing_imports = True
ignore_errors = True

[mypy-lsst.sphgeom._yaml]
ignore_errors = True
