# This file is part of sphgeom.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (http://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This software is dual licensed under the GNU General Public License and also
# under a 3-clause BSD license. Recipients may choose which of these licenses
# to use; please see the files gpl-3.0.txt and/or bsd_license.txt,
# respectively.  If you choose the GPL option then the following text applies
# (but note that there is still no warranty even if you opt for BSD instead):
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import collections.abc
import typing
from typing import ClassVar, overload

import numpy
import numpy.typing

from .pixelization_abc import PixelizationABC

# _relationship.cc
CONTAINS: int
DISJOINT: int
INTERSECTS: int
WITHIN: int

class Angle:
    @staticmethod
    def nan() -> Angle: ...
    @staticmethod
    def fromDegrees(degrees: float | int) -> Angle: ...
    @staticmethod
    def fromRadians(radians: float | int) -> Angle: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, radians: float | int) -> None: ...
    @overload
    def __init__(self, angle: Angle) -> None: ...
    @overload
    def __init__(self, normalizedAngle: NormalizedAngle) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, a: Angle) -> bool: ...
    def __gt__(self, a: Angle) -> bool: ...
    def __le__(self, a: Angle) -> bool: ...
    def __ge__(self, a: Angle) -> bool: ...
    def __neg__(self) -> Angle: ...
    def __add__(self, a: Angle) -> Angle: ...
    def __sub__(self, a: Angle) -> Angle: ...
    def __mul__(self, a: float | int) -> Angle: ...
    def __rmul__(self, a: float | int) -> Angle: ...
    @overload
    def __truediv__(self, a: float | int) -> Angle: ...
    @overload
    def __truediv__(self, a: Angle) -> float: ...
    def __iadd__(self, a: Angle) -> Angle: ...
    def __isub__(self, a: Angle) -> Angle: ...
    def __imul__(self, a: float | int) -> Angle: ...
    def __itruediv__(self, a: float | int) -> Angle: ...  # type: ignore[misc]
    def asDegrees(self) -> float: ...
    def asRadians(self) -> float: ...
    def isNan(self) -> bool: ...
    def isNormalized(self) -> bool: ...
    def __reduce__(self) -> tuple: ...

class AngleInterval:
    @staticmethod
    def fromDegrees(x: float | int, y: float | int) -> AngleInterval: ...
    @staticmethod
    def fromRadians(x: float | int, y: float | int) -> AngleInterval: ...
    @staticmethod
    def empty() -> AngleInterval: ...
    @staticmethod
    def full() -> AngleInterval: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: Angle) -> None: ...
    @overload
    def __init__(self, x: Angle, y: Angle) -> None: ...
    @overload
    def __init__(self, interval: AngleInterval) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def getA(self) -> Angle: ...
    def getB(self) -> Angle: ...
    def isEmpty(self) -> bool: ...
    def getCenter(self) -> Angle: ...
    def getSize(self) -> Angle: ...
    @overload
    def __contains__(self, angle: Angle) -> bool: ...
    @overload
    def __contains__(self, interval: AngleInterval) -> bool: ...
    @overload
    def contains(self, angle: Angle) -> bool: ...
    @overload
    def contains(self, interval: AngleInterval) -> bool: ...
    @overload
    def isDisjointFrom(self, angle: Angle) -> bool: ...
    @overload
    def isDisjointFrom(self, interval: AngleInterval) -> bool: ...
    @overload
    def intersects(self, angle: Angle) -> bool: ...
    @overload
    def intersects(self, interval: AngleInterval) -> bool: ...
    @overload
    def isWithin(self, angle: Angle) -> bool: ...
    @overload
    def isWithin(self, interval: AngleInterval) -> bool: ...
    @overload
    def relate(self, angle: Angle) -> int: ...
    @overload
    def relate(self, interval: AngleInterval) -> int: ...
    @overload
    def clipTo(self, angle: Angle) -> AngleInterval: ...
    @overload
    def clipTo(self, interval: AngleInterval) -> AngleInterval: ...
    @overload
    def clippedTo(self, angle: Angle) -> AngleInterval: ...
    @overload
    def clippedTo(self, interval: AngleInterval) -> AngleInterval: ...
    @overload
    def expandTo(self, angle: Angle) -> AngleInterval: ...
    @overload
    def expandTo(self, interval: AngleInterval) -> AngleInterval: ...
    @overload
    def expandedTo(self, angle: Angle) -> AngleInterval: ...
    @overload
    def expandedTo(self, interval: AngleInterval) -> AngleInterval: ...
    def dilateBy(self, angle: Angle) -> AngleInterval: ...
    def dilatedBy(self, angle: Angle) -> AngleInterval: ...
    def erodeBy(self, angle: Angle) -> AngleInterval: ...
    def erodedBy(self, angle: Angle) -> AngleInterval: ...
    def __reduce__(self) -> tuple: ...

class Box(Region):
    TYPE_CODE: ClassVar[int] = ...
    @staticmethod
    def fromDegrees(
        lon1: float | int,
        lat1: float | int,
        lon2: float | int,
        lat2: float | int,
    ) -> Box: ...
    @staticmethod
    def fromRadians(
        lon1: float | int,
        lat1: float | int,
        lon2: float | int,
        lat2: float | int,
    ) -> Box: ...
    @staticmethod
    def empty() -> Box: ...
    @staticmethod
    def full() -> Box: ...
    @staticmethod
    def halfWidthForCircle(radius: Angle, lat: Angle) -> NormalizedAngle: ...
    @staticmethod
    def allLatitudes() -> AngleInterval: ...
    @staticmethod
    def allLongitudes() -> NormalizedAngleInterval: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, point: LonLat) -> None: ...
    @overload
    def __init__(self, point1: LonLat, point2: LonLat) -> None: ...
    @overload
    def __init__(self, center: LonLat, width: Angle, height: Angle) -> None: ...
    @overload
    def __init__(self, lon: NormalizedAngleInterval, lat: AngleInterval) -> None: ...
    @overload
    def __init__(self, box: Box) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @overload
    def __contains__(self, uv3d: UnitVector3d) -> bool: ...
    @overload
    def __contains__(self, lon_lat: LonLat) -> bool: ...
    @overload
    def __contains__(self, box: Box) -> bool: ...
    def getLon(self) -> NormalizedAngleInterval: ...
    def getLat(self) -> AngleInterval: ...
    def isFull(self) -> bool: ...
    def getCenter(self) -> LonLat: ...
    def getWidth(self) -> NormalizedAngle: ...
    def getHeight(self) -> Angle: ...
    @overload
    def contains(self, unitVector: UnitVector3d) -> bool: ...
    @overload
    def contains(
        self,
        x: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        y: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def contains(
        self,
        lon: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        lat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def contains(self, lon_lat: LonLat) -> bool: ...
    @overload
    def contains(self, box: Box) -> bool: ...
    @overload
    def isDisjointFrom(self, lon_lat: LonLat) -> bool: ...
    @overload
    def isDisjointFrom(self, box: Box) -> bool: ...
    @overload
    def intersects(self, lon_lat: LonLat) -> bool: ...
    @overload
    def intersects(self, box: Box) -> bool: ...
    @overload
    def isWithin(self, lon_lat: LonLat) -> bool: ...
    @overload
    def isWithin(self, box: Box) -> bool: ...
    @overload
    def clipTo(self, lon_lat: LonLat) -> Box: ...
    @overload
    def clipTo(self, box: Box) -> Box: ...
    @overload
    def clippedTo(self, lon_lat: LonLat) -> Box: ...
    @overload
    def clippedTo(self, box: Box) -> Box: ...
    @overload
    def expandTo(self, lon_lat: LonLat) -> Box: ...
    @overload
    def expandTo(self, box: Box) -> Box: ...
    @overload
    def expandedTo(self, lon_lat: LonLat) -> Box: ...
    @overload
    def expandedTo(self, box: Box) -> Box: ...
    @overload
    def dilateBy(self, angle: Angle) -> Box: ...
    @overload
    def dilateBy(self, width: Angle, height: Angle) -> Box: ...
    @overload
    def dilatedBy(self, angle: Angle) -> Box: ...
    @overload
    def dilatedBy(self, width: Angle, height: Angle) -> Box: ...
    @overload
    def erodeBy(self, angle: Angle) -> Box: ...
    @overload
    def erodeBy(self, width: Angle, height: Angle) -> Box: ...
    @overload
    def erodedBy(self, angle: Angle) -> Box: ...
    @overload
    def erodedBy(self, width: Angle, height: Angle) -> Box: ...
    def getArea(self) -> float: ...
    @overload
    def relate(self, point: LonLat) -> int: ...
    @overload
    def relate(self, region: Region) -> int: ...

class Box3d:
    @staticmethod
    def empty() -> Box3d: ...
    @staticmethod
    def full() -> Box3d: ...
    @staticmethod
    def aroundUnitSphere() -> Box3d: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, vector: Vector3d) -> None: ...
    @overload
    def __init__(self, vector1: Vector3d, vector2: Vector3d) -> None: ...
    @overload
    def __init__(
        self,
        center: Vector3d,
        halfWidth: float | int,
        halfHeight: float | int,
        halfDepth: float | int,
    ) -> None: ...
    @overload
    def __init__(self, x: Interval1d, y: Interval1d, z: Interval1d) -> None: ...
    @overload
    def __init__(self, box3d: Box3d) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @overload
    def __contains__(self, v3d: Vector3d) -> bool: ...
    @overload
    def __contains__(self, box3d: Box3d) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> Interval1d: ...
    def __iter__(self) -> collections.abc.Iterator[Interval1d]: ...
    def x(self) -> Interval1d: ...
    def y(self) -> Interval1d: ...
    def z(self) -> Interval1d: ...
    def isEmpty(self) -> bool: ...
    def isFull(self) -> bool: ...
    def getCenter(self) -> Vector3d: ...
    def getWidth(self) -> float: ...
    def getHeight(self) -> float: ...
    def getDepth(self) -> float: ...
    @overload
    def contains(self, v3d: Vector3d) -> bool: ...
    @overload
    def contains(self, box3d: Box3d) -> bool: ...
    @overload
    def contains(
        self,
        x: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        y: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def isDisjointFrom(self, v3d: Vector3d) -> bool: ...
    @overload
    def isDisjointFrom(self, box3d: Box3d) -> bool: ...
    @overload
    def intersects(self, v3d: Vector3d) -> bool: ...
    @overload
    def intersects(self, box3d: Box3d) -> bool: ...
    @overload
    def isWithin(self, v3d: Vector3d) -> bool: ...
    @overload
    def isWithin(self, box3d: Box3d) -> bool: ...
    @overload
    def clipTo(self, v3d: Vector3d) -> Box3d: ...
    @overload
    def clipTo(self, box3d: Box3d) -> Box3d: ...
    @overload
    def clippedTo(self, v3d: Vector3d) -> Box3d: ...
    @overload
    def clippedTo(self, box3d: Box3d) -> Box3d: ...
    @overload
    def expandTo(self, v3d: Vector3d) -> Box3d: ...
    @overload
    def expandTo(self, box3d: Box3d) -> Box3d: ...
    @overload
    def expandedTo(self, v3d: Vector3d) -> Box3d: ...
    @overload
    def expandedTo(self, box3d: Box3d) -> Box3d: ...
    @overload
    def dilateBy(self, radius: float | int) -> Box3d: ...
    @overload
    def dilateBy(self, width: float | int, height: float | int, depth: float | int) -> Box3d: ...
    @overload
    def dilatedBy(self, radius: float | int) -> Box3d: ...
    @overload
    def dilatedBy(self, width: float | int, height: float | int, depth: float | int) -> Box3d: ...
    @overload
    def erodeBy(self, radius: float | int) -> Box3d: ...
    @overload
    def erodeBy(self, width: float | int, height: float | int, depth: float | int) -> Box3d: ...
    @overload
    def erodedBy(self, radius: float | int) -> Box3d: ...
    @overload
    def erodedBy(self, width: float | int, height: float | int, depth: float | int) -> Box3d: ...
    @overload
    def relate(self, v3d: Vector3d) -> int: ...
    @overload
    def relate(self, box3d: Box3d) -> int: ...
    def __reduce__(self) -> tuple: ...

class Chunker:
    def __init__(self, numStripes: int, numSubStripesPerStripe: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def numStripes(self) -> int: ...
    @property
    def numSubStripesPerStripe(self) -> int: ...
    def getChunksIntersecting(self, region: Region) -> list[int]: ...
    def getSubChunksIntersecting(self, region: Region) -> list[tuple[int, list[int]]]: ...
    def getAllChunks(self) -> list[int]: ...
    def getAllSubChunks(self, chunkId: int) -> list[int]: ...
    def getChunkBoundingBox(self, stripe: int, chunk: int) -> Box: ...
    def getSubChunkBoundingBox(self, subStripe: int, subChunk: int) -> Box: ...
    def getStripe(self, chunkId: int) -> int: ...
    def getChunk(self, chunkId: int, stripe: int) -> int: ...
    def __reduce__(self) -> tuple: ...

class Circle(Region):
    TYPE_CODE: ClassVar[int] = ...
    @staticmethod
    def empty() -> Circle: ...
    @staticmethod
    def full() -> Circle: ...
    @staticmethod
    def squaredChordLengthFor(openingAngle: Angle) -> float: ...
    @staticmethod
    def openingAngleFor(squaredChordLength: float | int) -> Angle: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, center: UnitVector3d) -> None: ...
    @overload
    def __init__(self, center: UnitVector3d, angle: Angle) -> None: ...
    @overload
    def __init__(self, center: UnitVector3d, squaredChordLength: float | int) -> None: ...
    @overload
    def __init__(self, circle: Circle) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @overload
    def __contains__(self, uv3d: UnitVector3d) -> bool: ...
    @overload
    def __contains__(self, circle: Circle) -> bool: ...
    def isFull(self) -> bool: ...
    def getCenter(self) -> UnitVector3d: ...
    def getSquaredChordLength(self) -> float: ...
    def getOpeningAngle(self) -> Angle: ...
    @overload
    def contains(self, unitVector: UnitVector3d) -> bool: ...
    @overload
    def contains(
        self,
        x: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        y: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def contains(
        self,
        lon: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        lat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def contains(self, circle: Circle) -> bool: ...
    @overload
    def isDisjointFrom(self, uv3d: UnitVector3d) -> bool: ...
    @overload
    def isDisjointFrom(self, circle: Circle) -> bool: ...
    @overload
    def intersects(self, uv3d: UnitVector3d) -> bool: ...
    @overload
    def intersects(self, circle: Circle) -> bool: ...
    @overload
    def isWithin(self, uv3d: UnitVector3d) -> bool: ...
    @overload
    def isWithin(self, circle: Circle) -> bool: ...
    @overload
    def clipTo(self, uv3d: UnitVector3d) -> Circle: ...
    @overload
    def clipTo(self, circle: Circle) -> Circle: ...
    @overload
    def clippedTo(self, uv3d: UnitVector3d) -> Circle: ...
    @overload
    def clippedTo(self, circle: Circle) -> Circle: ...
    @overload
    def expandTo(self, uv3d: UnitVector3d) -> Circle: ...
    @overload
    def expandTo(self, circle: Circle) -> Circle: ...
    @overload
    def expandedTo(self, uv3d: UnitVector3d) -> Circle: ...
    @overload
    def expandedTo(self, circle: Circle) -> Circle: ...
    def dilateBy(self, radius: Angle) -> Circle: ...
    def dilatedBy(self, radius: Angle) -> Circle: ...
    def erodeBy(self, radius: Angle) -> Circle: ...
    def erodedBy(self, radius: Angle) -> Circle: ...
    def getArea(self) -> float: ...
    def complement(self) -> Circle: ...
    def complemented(self) -> Circle: ...

class CompoundRegion(Region):
    def cloneOperand(self, index: int) -> Region: ...
    def nOperands(self) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[Region]: ...
    def __len__(self) -> int: ...

class ConvexPolygon(Region):
    TYPE_CODE: ClassVar[int] = ...
    @staticmethod
    def convexHull(points: collections.abc.Sequence[UnitVector3d]) -> ConvexPolygon: ...
    @overload
    def __init__(self, points: collections.abc.Sequence[UnitVector3d]) -> None: ...
    @overload
    def __init__(self, convexPolygon: ConvexPolygon) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def getVertices(self) -> list[UnitVector3d]: ...
    def getCentroid(self) -> UnitVector3d: ...
    @overload
    def contains(self, unitVector: UnitVector3d) -> bool: ...
    @overload
    def contains(
        self,
        x: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        y: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def contains(
        self,
        lon: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        lat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def contains(self, region: Region) -> bool: ...
    def isDisjointFrom(self, region: Region) -> bool: ...
    def intersects(self, region: Region) -> bool: ...
    def isWithin(self, region: Region) -> bool: ...

class Ellipse(Region):
    TYPE_CODE: ClassVar[int] = ...
    @staticmethod
    def empty() -> Ellipse: ...
    @staticmethod
    def full() -> Ellipse: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, circle: Circle) -> None: ...
    @overload
    def __init__(self, center: UnitVector3d, angle: Angle = ...) -> None: ...
    @overload
    def __init__(self, focus1: UnitVector3d, focus2: UnitVector3d, alpha: Angle) -> None: ...
    @overload
    def __init__(self, center: UnitVector3d, alpha: Angle, beta: Angle, orientation: Angle) -> None: ...
    @overload
    def __init__(self, ellipse: Ellipse) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def isFull(self) -> bool: ...
    def isGreatCircle(self) -> bool: ...
    def isCircle(self) -> bool: ...
    def getTransformMatrix(self) -> Matrix3d: ...
    def getCenter(self) -> UnitVector3d: ...
    def getF1(self) -> UnitVector3d: ...
    def getF2(self) -> UnitVector3d: ...
    def getAlpha(self) -> Angle: ...
    def getBeta(self) -> Angle: ...
    def getGamma(self) -> Angle: ...
    def complement(self) -> Ellipse: ...
    def complemented(self) -> Ellipse: ...

class HtmPixelization(Pixelization):
    MAX_LEVEL: ClassVar[int] = ...
    @staticmethod
    def level(i: int) -> int: ...
    @staticmethod
    def triangle(i: int) -> ConvexPolygon: ...
    @staticmethod
    def asString(i: int) -> str: ...
    @overload
    def __init__(self, level: int) -> None: ...
    @overload
    def __init__(self, htmPixelization: HtmPixelization) -> None: ...
    def getLevel(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self) -> tuple: ...

class IntersectionRegion(CompoundRegion):
    TYPE_CODE: ClassVar[int] = ...
    def __init__(self, *args: Region) -> None: ...

class Interval1d:
    @staticmethod
    def empty() -> Interval1d: ...
    @staticmethod
    def full() -> Interval1d: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float | int) -> None: ...
    @overload
    def __init__(self, x: float | int, y: float | int) -> None: ...
    @overload
    def __init__(self, interval: Interval1d) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def getA(self) -> float: ...
    def getB(self) -> float: ...
    def isEmpty(self) -> bool: ...
    def isFull(self) -> bool: ...
    def getCenter(self) -> float: ...
    def getSize(self) -> float: ...
    @overload
    def __contains__(self, v: float | int) -> bool: ...
    @overload
    def __contains__(self, interval: Interval1d) -> bool: ...
    @overload
    def contains(self, v: float | int) -> bool: ...
    @overload
    def contains(self, interval: Interval1d) -> bool: ...
    @overload
    def isDisjointFrom(self, v: float | int) -> bool: ...
    @overload
    def isDisjointFrom(self, interval: Interval1d) -> bool: ...
    @overload
    def intersects(self, v: float | int) -> bool: ...
    @overload
    def intersects(self, interval: Interval1d) -> bool: ...
    @overload
    def isWithin(self, v: float | int) -> bool: ...
    @overload
    def isWithin(self, interval: Interval1d) -> bool: ...
    @overload
    def relate(self, v: float | int) -> int: ...
    @overload
    def relate(self, interval: Interval1d) -> int: ...
    @overload
    def clipTo(self, v: float | int) -> Interval1d: ...
    @overload
    def clipTo(self, interval: Interval1d) -> Interval1d: ...
    @overload
    def clippedTo(self, v: float | int) -> Interval1d: ...
    @overload
    def clippedTo(self, interval: Interval1d) -> Interval1d: ...
    @overload
    def expandTo(self, v: float | int) -> Interval1d: ...
    @overload
    def expandTo(self, interval: Interval1d) -> Interval1d: ...
    @overload
    def expandedTo(self, v: float | int) -> Interval1d: ...
    @overload
    def expandedTo(self, interval: Interval1d) -> Interval1d: ...
    def dilateBy(self, v: float | int) -> Interval1d: ...
    def dilatedBy(self, v: float | int) -> Interval1d: ...
    def erodeBy(self, v: float | int) -> Interval1d: ...
    def erodedBy(self, v: float | int) -> Interval1d: ...
    def __reduce__(self) -> tuple: ...

class LonLat:
    @staticmethod
    def fromDegrees(lon: float | int, lat: float | int) -> LonLat: ...
    @staticmethod
    def fromRadians(lon: float | int, lat: float | int) -> LonLat: ...
    @staticmethod
    def latitudeOf(v3d: Vector3d) -> Angle: ...
    @staticmethod
    def longitudeOf(v3d: Vector3d) -> NormalizedAngle: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, lon_lat: LonLat) -> None: ...
    @overload
    def __init__(self, lon: NormalizedAngle, lat: Angle) -> None: ...
    @overload
    def __init__(self, vector: Vector3d) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def getLat(self) -> Angle: ...
    def getLon(self) -> NormalizedAngle: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: object) -> float: ...
    def __iter__(self) -> collections.abc.Iterator[float]: ...
    def __reduce__(self) -> tuple: ...

class Matrix3d:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        m00: float | int,
        m01: float | int,
        m02: float | int,
        m10: float | int,
        m11: float | int,
        m12: float | int,
        m20: float | int,
        m21: float | int,
        m22: float | int,
    ) -> None: ...
    @overload
    def __init__(self, diagonal: Vector3d) -> None: ...
    @overload
    def __init__(self, scale: float | int) -> None: ...
    @overload
    def __init__(self, matrix: Matrix3d) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def getColumn(self, col: int) -> Vector3d: ...
    def getRow(self, row: int) -> Vector3d: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[Vector3d]: ...
    @overload
    def __getitem__(self, index: int) -> Vector3d: ...
    @overload
    def __getitem__(self, indices: tuple) -> Matrix3d | Vector3d | float: ...
    def inner(self, matrix: Matrix3d) -> float: ...
    def getSquaredNorm(self) -> float: ...
    def getNorm(self) -> float: ...
    @overload
    def __mul__(self, vector: Vector3d) -> Vector3d: ...
    @overload
    def __mul__(self, matrix: Matrix3d) -> Matrix3d: ...
    def __add__(self, matrix: Matrix3d) -> Matrix3d: ...
    def __sub__(self, matrix: Matrix3d) -> Matrix3d: ...
    def cwiseProduct(self, matrix: Matrix3d) -> Matrix3d: ...
    def transpose(self) -> Matrix3d: ...
    def inverse(self) -> Matrix3d: ...
    def __reduce__(self) -> tuple: ...

class Mq3cPixelization(Pixelization):
    MAX_LEVEL: ClassVar[int] = ...
    @overload
    def __init__(self, level: int) -> None: ...
    @overload
    def __init__(self, mq3cPixelization: Mq3cPixelization) -> None: ...
    @staticmethod
    def level(index: int) -> int: ...
    @staticmethod
    def quad(index: int) -> ConvexPolygon: ...
    @staticmethod
    def neighborhood(index: int) -> list[int]: ...
    @staticmethod
    def asString(index: int) -> str: ...
    def getLevel(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self) -> tuple: ...

class NormalizedAngle:
    @staticmethod
    def nan() -> NormalizedAngle: ...
    @staticmethod
    def fromDegrees(degrees: float | int) -> NormalizedAngle: ...
    @staticmethod
    def fromRadians(radians: float | int) -> NormalizedAngle: ...
    @staticmethod
    def between(a: NormalizedAngle, b: NormalizedAngle) -> NormalizedAngle: ...
    @staticmethod
    def center(a: NormalizedAngle, b: NormalizedAngle) -> NormalizedAngle: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, angle: NormalizedAngle) -> None: ...
    @overload
    def __init__(self, angle: Angle) -> None: ...
    @overload
    def __init__(self, radians: float | int) -> None: ...
    @overload
    def __init__(self, a: LonLat, b: LonLat) -> None: ...
    @overload
    def __init__(self, a: Vector3d, b: Vector3d) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, angle: Angle) -> bool: ...
    def __gt__(self, angle: Angle) -> bool: ...
    def __le__(self, angle: Angle) -> bool: ...
    def __ge__(self, angle: Angle) -> bool: ...
    def __neg__(self) -> Angle: ...
    def __add__(self, angle: Angle) -> Angle: ...
    def __sub__(self, angle: Angle) -> Angle: ...
    def __mul__(self, v: float | int) -> Angle: ...
    def __rmul__(self, v: float | int) -> Angle: ...
    @overload
    def __truediv__(self, v: float | int) -> Angle: ...
    @overload
    def __truediv__(self, angle: Angle) -> float: ...
    def asDegrees(self) -> float: ...
    def asRadians(self) -> float: ...
    def isNan(self) -> bool: ...
    def getAngleTo(self, angle: NormalizedAngle) -> NormalizedAngle: ...
    def __reduce__(self) -> tuple: ...

class NormalizedAngleInterval:
    @staticmethod
    def fromDegrees(x: float | int, y: float | int) -> NormalizedAngleInterval: ...
    @staticmethod
    def fromRadians(x: float | int, y: float | int) -> NormalizedAngleInterval: ...
    @staticmethod
    def empty() -> NormalizedAngleInterval: ...
    @staticmethod
    def full() -> NormalizedAngleInterval: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: Angle) -> None: ...
    @overload
    def __init__(self, x: NormalizedAngle) -> None: ...
    @overload
    def __init__(self, x: Angle, y: Angle) -> None: ...
    @overload
    def __init__(self, x: NormalizedAngle, y: NormalizedAngle) -> None: ...
    @overload
    def __init__(self, angleInterval: NormalizedAngleInterval) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def getA(self) -> NormalizedAngle: ...
    def getB(self) -> NormalizedAngle: ...
    def isEmpty(self) -> bool: ...
    def isFull(self) -> bool: ...
    def getCenter(self) -> NormalizedAngle: ...
    def getSize(self) -> NormalizedAngle: ...
    @overload
    def __contains__(self, angle: NormalizedAngle) -> bool: ...
    @overload
    def __contains__(self, interval: NormalizedAngleInterval) -> bool: ...
    @overload
    def contains(self, angle: NormalizedAngle) -> bool: ...
    @overload
    def contains(self, interval: NormalizedAngleInterval) -> bool: ...
    @overload
    def isDisjointFrom(self, angle: NormalizedAngle) -> bool: ...
    @overload
    def isDisjointFrom(self, interval: NormalizedAngleInterval) -> bool: ...
    @overload
    def intersects(self, angle: NormalizedAngle) -> bool: ...
    @overload
    def intersects(self, interval: NormalizedAngleInterval) -> bool: ...
    @overload
    def isWithin(self, angle: NormalizedAngle) -> bool: ...
    @overload
    def isWithin(self, interval: NormalizedAngleInterval) -> bool: ...
    @overload
    def relate(self, angle: NormalizedAngle) -> int: ...
    @overload
    def relate(self, interval: NormalizedAngleInterval) -> int: ...
    @overload
    def clipTo(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    @overload
    def clipTo(self, interval: NormalizedAngleInterval) -> NormalizedAngleInterval: ...
    @overload
    def clippedTo(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    @overload
    def clippedTo(self, interval: NormalizedAngleInterval) -> NormalizedAngleInterval: ...
    @overload
    def expandTo(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    @overload
    def expandTo(self, interval: NormalizedAngleInterval) -> NormalizedAngleInterval: ...
    @overload
    def expandedTo(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    @overload
    def expandedTo(self, interval: NormalizedAngleInterval) -> NormalizedAngleInterval: ...
    def dilateBy(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    def dilatedBy(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    def erodeBy(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    def erodedBy(self, angle: NormalizedAngle) -> NormalizedAngleInterval: ...
    def wraps(self) -> bool: ...
    def __reduce__(self) -> tuple: ...

class Pixelization(PixelizationABC):
    def universe(self) -> RangeSet: ...
    def pixel(self, index: int) -> Region: ...
    def index(self, uv3d: UnitVector3d) -> int: ...
    def envelope(self, region: Region, maxRanges: int = 0) -> RangeSet: ...
    def interior(self, region: Region, maxRanges: int = 0) -> RangeSet: ...
    def toString(self, index: int) -> str: ...

class Q3cPixelization(Pixelization):
    MAX_LEVEL: ClassVar[int] = ...
    @overload
    def __init__(self, level: int) -> None: ...
    @overload
    def __init__(self, q3cPixelization: Q3cPixelization) -> None: ...
    def getLevel(self) -> int: ...
    def neighborhood(self, index: int) -> list[int]: ...
    def quad(self, index: int) -> ConvexPolygon: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self) -> tuple: ...

class RangeSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, integer: int) -> None: ...
    @overload
    def __init__(self, first: int, last: int) -> None: ...
    @overload
    def __init__(self, rangeSet: RangeSet) -> None: ...
    @overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @overload
    def insert(self, integer: int) -> None: ...
    @overload
    def insert(self, first: int, last: int) -> None: ...
    @overload
    def erase(self, integer: int) -> None: ...
    @overload
    def erase(self, first: int, last: int) -> None: ...
    def complement(self) -> RangeSet: ...
    def complemented(self) -> RangeSet: ...
    def intersection(self, rangeSet: RangeSet) -> RangeSet: ...
    def difference(self, rangeSet: RangeSet) -> RangeSet: ...
    def union(self, rangeSet: RangeSet) -> RangeSet: ...
    def symmetricDifference(self, rangeSet: RangeSet) -> RangeSet: ...
    def __invert__(self) -> RangeSet: ...
    def __and__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __or__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __sub__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __xor__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __iand__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __ior__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __isub__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __ixor__(self, rangeSet: RangeSet) -> RangeSet: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> tuple[int, int]: ...
    def __iter__(self) -> collections.abc.Iterator[tuple[int, int]]: ...
    @overload
    def intersects(self, integer: int) -> bool: ...
    @overload
    def intersects(self, first: int, last: int) -> bool: ...
    @overload
    def intersects(self, rangeSet: RangeSet) -> bool: ...
    @overload
    def contains(self, integer: int) -> bool: ...
    @overload
    def contains(self, first: int, last: int) -> bool: ...
    @overload
    def contains(self, rangeSet: RangeSet) -> bool: ...
    @overload
    def __contains__(self, integer: int) -> bool: ...
    @overload
    def __contains__(self, first: int, last: int) -> bool: ...
    @overload
    def __contains__(self, rangeSet: RangeSet) -> bool: ...
    @overload
    def isWithin(self, integer: int) -> bool: ...
    @overload
    def isWithin(self, first: int, last: int) -> bool: ...
    @overload
    def isWithin(self, rangeSet: RangeSet) -> bool: ...
    @overload
    def isDisjointFrom(self, integer: int) -> bool: ...
    @overload
    def isDisjointFrom(self, first: int, last: int) -> bool: ...
    @overload
    def isDisjointFrom(self, rangeSet: RangeSet) -> bool: ...
    def simplify(self, n: int) -> RangeSet: ...
    def simplified(self, n: int) -> RangeSet: ...
    def scale(self, factor: int) -> RangeSet: ...
    def scaled(self, factor: int) -> RangeSet: ...
    def fill(self) -> None: ...
    def clear(self) -> None: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
    def size(self) -> int: ...
    def cardinality(self) -> int: ...
    def isValid(self) -> int: ...
    def ranges(self) -> list[tuple[int, int]]: ...
    def __reduce__(self) -> tuple: ...

class Region:
    @classmethod
    def from_ivoa_pos(cls, pos: str) -> Region: ...
    def clone(self) -> Region: ...
    def isEmpty(self) -> bool: ...
    def getBoundingBox(self) -> Box: ...
    def getBoundingBox3d(self) -> Box3d: ...
    def getBoundingCircle(self) -> Circle: ...
    @overload
    def contains(self, unitVector: UnitVector3d) -> bool: ...
    @overload
    def contains(
        self,
        x: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        y: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    @overload
    def contains(
        self,
        lon: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
        lat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    ) -> typing.Annotated[numpy.typing.ArrayLike, numpy.bool_]: ...
    def __contains__(self, uv3d: UnitVector3d) -> bool: ...
    def relate(self, region: Region) -> int: ...
    def overlaps(self, region: Region) -> bool | None: ...
    def encode(self) -> bytes: ...
    @staticmethod
    def decode(bytes: bytes) -> Region: ...
    @staticmethod
    def decodeBase64(bytes: str) -> Region: ...
    @staticmethod
    def decodeOverlapsBase64(bytes: str) -> bool | None: ...
    @staticmethod
    def getRegions(region: Region) -> list[Region]: ...
    def to_ivoa_stcs(self, frame: str = ...) -> str: ...
    def to_ivoa_pos(self) -> str: ...

class UnionRegion(CompoundRegion):
    TYPE_CODE: ClassVar[int] = ...
    def __init__(self, *args: Region) -> None: ...

class UnitVector3d:
    @overload
    @staticmethod
    def orthogonalTo(vector: Vector3d) -> UnitVector3d: ...
    @overload
    @staticmethod
    def orthogonalTo(vector1: Vector3d, vector2: Vector3d) -> UnitVector3d: ...
    @overload
    @staticmethod
    def orthogonalTo(meridian: NormalizedAngle) -> UnitVector3d: ...
    @staticmethod
    def northFrom(vector: Vector3d) -> UnitVector3d: ...
    @staticmethod
    def X() -> UnitVector3d: ...
    @staticmethod
    def Y() -> UnitVector3d: ...
    @staticmethod
    def Z() -> UnitVector3d: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, unitVector: UnitVector3d) -> None: ...
    @overload
    def __init__(self, vector: Vector3d) -> None: ...
    @overload
    def __init__(self, x: float | int, y: float | int, z: float | int) -> None: ...
    @overload
    def __init__(self, lonLat: LonLat) -> None: ...
    @overload
    def __init__(self, lon: Angle, lat: Angle) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self) -> UnitVector3d: ...
    def __add__(self, v3d: Vector3d) -> Vector3d: ...
    def __sub__(self, v3d: Vector3d) -> Vector3d: ...
    def __mul__(self, v: float | int) -> Vector3d: ...
    def __truediv__(self, v: float | int) -> Vector3d: ...
    @overload
    def x(self) -> float: ...
    @overload
    def x(self, v3d: Vector3d) -> float: ...
    def y(self) -> float: ...
    def z(self) -> float: ...
    def dot(self, v3d: Vector3d) -> float: ...
    def cross(self, v3d: Vector3d) -> Vector3d: ...
    def robustCross(self, uv3d: UnitVector3d) -> Vector3d: ...
    def cwiseProduct(self, v3d: Vector3d) -> Vector3d: ...
    def rotatedAround(self, axis: UnitVector3d, angle: Angle) -> UnitVector3d: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> float: ...
    def __iter__(self) -> collections.abc.Iterator[float]: ...

class Vector3d:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float | int, y: float | int, z: float | int) -> None: ...
    @overload
    def __init__(self, vector: Vector3d) -> None: ...
    @overload
    def __init__(self, uv3d: UnitVector3d) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self) -> Vector3d: ...
    def __add__(self, v3d: Vector3d) -> Vector3d: ...
    def __sub__(self, v3d: Vector3d) -> Vector3d: ...
    def __mul__(self, v: float | int) -> Vector3d: ...
    def __truediv__(self, v: float | int) -> Vector3d: ...
    def __iadd__(self, v3d: Vector3d) -> Vector3d: ...
    def __isub__(self, v3d: Vector3d) -> Vector3d: ...
    def __imul__(self, f: float | int) -> Vector3d: ...
    def __itruediv__(self, f: float | int) -> Vector3d: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def z(self) -> float: ...
    def dot(self, v3d: Vector3d) -> float: ...
    def getSquaredNorm(self) -> float: ...
    def getNorm(self) -> float: ...
    def isZero(self) -> bool: ...
    def normalize(self) -> float: ...
    def isNormalized(self) -> bool: ...
    def cross(self, v3d: Vector3d) -> Vector3d: ...
    def cwiseProduct(self, v3d: Vector3d) -> Vector3d: ...
    def rotatedAround(self, axis: UnitVector3d, angle: Angle) -> Vector3d: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> float: ...
    def __iter__(self) -> collections.abc.Iterator[float]: ...
    def __reduce__(self) -> tuple: ...

# _curve.cc
def log2(v: int) -> int: ...
def mortonIndex(x: int, y: int) -> int: ...
def mortonIndexInverse(z: int) -> tuple[int, int]: ...
def mortonToHilbert(z: int, m: int) -> int: ...
def hilbertToMorton(h: int, m: int) -> int: ...
def hilbertIndex(x: int, y: int, m: int) -> int: ...
def hilbertIndexInverse(h: int, m: int) -> tuple[int, int]: ...

# _utils.cc
def getMinSquaredChordLength(v: Vector3d, a: Vector3d, b: Vector3d, n: Vector3d) -> float: ...
def getMaxSquaredChordLength(v: Vector3d, a: Vector3d, b: Vector3d, n: Vector3d) -> float: ...
def getMinAngleToCircle(x: Angle, c: Angle) -> Angle: ...
def getMaxAngleToCircle(x: Angle, c: Angle) -> Angle: ...
def getWeightedCentroid(vector0: UnitVector3d, vector1: UnitVector3d, vector2: UnitVector3d) -> Vector3d: ...

# _orientation.cc
def orientationExact(a: Vector3d, b: Vector3d, c: Vector3d) -> int: ...
def orientation(a: UnitVector3d, b: UnitVector3d, c: UnitVector3d) -> int: ...
def orientationX(b: UnitVector3d, c: UnitVector3d) -> int: ...
def orientationY(b: UnitVector3d, c: UnitVector3d) -> int: ...
def orientationZ(b: UnitVector3d, c: UnitVector3d) -> int: ...

# _relationship.cc
def invert(relationship: int) -> int: ...
