from lsst.sconsUtils import scripts

scripts.BasicSConscript.pybind11(
    ["_sphgeom"],
    extraSrc={
        "_sphgeom": [
            "_angle.cc",
            "_angleInterval.cc",
            "_box.cc",
            "_box3d.cc",
            "_chunker.cc",
            "_circle.cc",
            "_convexPolygon.cc",
            "_curve.cc",
            "_ellipse.cc",
            "_htmPixelization.cc",
            "_interval1d.cc",
            "_lonLat.cc",
            "_matrix3d.cc",
            "_mq3cPixelization.cc",
            "_normalizedAngle.cc",
            "_normalizedAngleInterval.cc",
            "_orientation.cc",
            "_pixelization.cc",
            "_q3cPixelization.cc",
            "_rangeSet.cc",
            "_region.cc",
            "_relationship.cc",
            "_unitVector3d.cc",
            "_utils.cc",
            "_vector3d.cc",
        ]
    },
    addUnderscore=False
)
