Import('env')

env = env.Clone()
headers = env.Glob('*.h')
sources = env.Glob('*.cc')
sphgeomStatic = env.StaticLibrary('sphgeom', sources)
sphgeomShared = env.SharedLibrary('sphgeom', sources)
env.Install('$LIBDIR', [sphgeomStatic, sphgeomShared])
env.Install('$INCLUDEDIR', headers)

# By default, only build the libraries.
env.Default([sphgeomStatic, sphgeomShared])
