name: build_and_test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything to determine version from git.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Build and install
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[yaml,test]

      - name: Run tests
        run: pytest -r a -v
