name: build_and_test

on:
  - push
  - pull_request

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build and install
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[yaml,test]

      - name: Run tests
        run: pytest -r a -v
