name: cmake

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-workflow:
    uses: lsst/rubin_workflows/.github/workflows/cmake.yaml@tickets/DM-35133
    with:
      pip_deps: "numpy pybind11[global] pyyaml healpy"
