name: Run pre-commit

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Run prek
        uses: j178/prek-action@v2
        with:
          extra_args: --all-files
